theme = "hugo-theme-learn"
baseURL = "http://flowctl.app/"
languageCode = "en-uk"
title = "flowcontrol"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "flowcontrol"
disableLandingPageButton = true
disableNextPrev = true
