---
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

name: Build Windows

jobs:
  build:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
# Install deps
      - name: Install wails dependencies
        if: ${{ env.ACT }}
        run: |
          sudo apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install keyboard-configuration
          sudo apt-get -y install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Install wails dependencies
        if: ${{ !env.ACT }}
        run: sudo apt-get -y install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
# Setup docker for wails cross-compile
      - uses: docker-practice/actions-setup-docker@master
# Setup go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: Install wails
        run: GO111MODULE=on go get -u github.com/wailsapp/wails/cmd/wails
      - name: Update to prerelease
        run: wails update -pre
# Compile wails app for darwin/amd64
      - name: Build project
        if: ${{ !env.ACT }}
        run: |
          cd ./src/flowcontrol
          wails build -x windows/amd64 --verbose
      # If building locally, ensure we don't compile for a specific architecture due to docker in docker requirements
      - name: Build project
        if: ${{ env.ACT }}
        run: |
          cd ./src/flowcontrol
          wails build
# Setup dotnet
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build flowcontrol-monitor
        working-directory: ./src/flowcontrol-monitor
        run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true --self-contained True
      - name: Copy compiled files
        run: cp -r ./src/flowcontrol-monitor/bin/Release/net5.0/win-x64/publish/ ./src/flowcontrol/build
