---
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
# Install deps
      - name: Install wails dependencies
        if: ${{ env.ACT }}
        run: |
          sudo apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install keyboard-configuration
          sudo apt-get -y install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Install wails dependencies
        if: ${{ !env.ACT }}
        run: sudo apt-get -y install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
# Setup docker for wails cross-compile
      - uses: docker-practice/actions-setup-docker@master
# Setup go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: Install wails
        run: GO111MODULE=on go get -u github.com/wailsapp/wails/cmd/wails@1.16.4-pre1
# Setup dotnet
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build flowcontrol-monitor
        working-directory: ./src/flowcontrol-monitor
        run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true --self-contained True
      - name: Copy compiled files
        run: cp -r ./src/flowcontrol-monitor/bin/Release/net5.0/win-x64/publish/ ./src/flowcontrol/build
# Compile wails app
      - name: Build project
        if: ${{ !env.ACT }}
        run: |
          cd ./src/flowcontrol
          wails build -x windows/amd64
      # If building locally, ensure we don't compile for a specific architecture due to docker in docker requirements
      - name: Build project
        if: ${{ env.ACT }}
        run: |
          cd ./src/flowcontrol
          wails build
      - name: Zip assets
        run: |
          zip -r flowcontrol.zip ./src/flowcontrol/build
          zip -r firmware.zip ./firmware
          cp flowcontrol.zip /home/runner/work/flowcontrol.zip
          cp firmware.zip /home/runner/work/firmware.zip
#Create release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
#Upload release assets
      - name: Upload desktop app asset
        id: upload-desktop-asset 
        uses: actions/upload-release-asset@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/flowcontrol.zip
          asset_name: flowcontrol-winx64.zip
          asset_content_type: application/zip
      - name: Upload firmware asset
        id: upload-firmware-asset 
        uses: actions/upload-release-asset@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/firmware.zip
          asset_name: firmware.zip
          asset_content_type: application/zip
